Feature/listagem apostas
NeoSolutions2022/Cassino pull request #4
Opened 2023-05-17 18:44 UTC by YohansN

## Task: Listagem de apostas | Administrador - (13/05 - 15/05)

##### Branch: Feature/listagem-apostas

Detalhamento: Rotas GET que buscam todas as apostas realizadas, seja por um usuario X ou geral.

**Aposta**: Alteração na renda do usuário (ocorre após um jogo).

* * *

### O que foi feito nessa branch:
  
* Criação da Table "Apostas":
  
* Método de criação de novo registro de aposta.

* Implementação desse método na service de Saldo para que sempre que o saldo do usuario for atualizado um novo registro de aposta seja criado.
  
* Método de busca de registros de aposta de um usuário específico.
  
* Método de busca de todos os registros de aposta.

* Rota de Busca para todas as apostas registradas e busca para todas as apostas de um usuario.

2023-05-24 13:35 UTC, NeoSolutions2022 requested changes
code review

2023-05-24 13:35 UTC, NeoSolutions2022 commented on backend/Cassino.Api/Controllers/Usuario/UsuarioSaldoController.cs
> +    public async Task<IActionResult> AtualizarSaldo([FromQuery] AdicionarApostaDto apostaDto)
É interessante usar "FromQuery" apenas para requisições de GET, no caso de envio de arquivos, "FromForm" é ideal, para requisições com dados padrões o "FromBody" fica mais interessante pro front

2023-05-24 13:35 UTC, NeoSolutions2022 commented on backend/Cassino.Domain/Entities/Aposta.cs
> +        Mines,
coloca ids ou descriptions

2023-05-24 13:35 UTC, NeoSolutions2022 commented on backend/Cassino.Infra/Repositories/ApostaRepository.cs
> +            await Context.Apostas.AddAsync(aposta);
operações de adicionar ou alterar entidades podem ser do tipo void mesmo

2023-05-24 13:35 UTC, NeoSolutions2022 commented on backend/Cassino.Domain/Entities/Aposta.cs
> +using System.Linq;
tua IDE tá colocando esses using por padrão?

2023-05-25 16:12 UTC, YohansN commented on backend/Cassino.Application/Services/SaldoService.cs
>          {
Falei com o Front (Pedro Ivo) e ele disse que é opcional mas vou implementar.

2023-06-02 19:07 UTC, YohansN commented
O que funciona
Buscar de Saldo
Envio de E-mail (Talvez, necessário teste e orações na homologação) 
Atualizar saldo retorna erro porem o saldo é atualizado (CONFIA!!)

O que não funciona (AINDA)
Rotas de listagem de aposta.

2023-06-02 19:08 UTC, merged